### ISSUE TITLE
Removing asset tags

### ISSUE THREAD

**Issue by andreasvirkus** [DustinJackson/html-webpack-inline-source-plugin#46]
Hi, thanks for the plugin and it works as intended (assets are inlined nicely), but for some reason
the script and link tags are kept in the resulting markup. Any way to remove them via this plugin or a common process that's used to remove them?

**Comment by w-flo** [comment]
I'm not sure if this is exactly what you're asking for, but my issue sounds similar. I use my own HTML file as a template for html-webpack, but I also want to be able to open that html file directly in a browser, so it includes my "source" script and css files using <script> and < link> tags. After processing the script files, style sheets and the HTML template using webpack, html-webpack and html-webpack-inline-source, I get a single HTML file (based on the template) with the inlined, minified JS/CSS. My issue was that, of course, the HTML file used as a template includes <script> and < link> tags, and obviously the webpack plugins can't tell which of those assets are now redundant / fail to load because the content is already inlined into the final HTML, and the source files are not in the dist directory. So it doesn't remove those tags.

There's a funny workaround I came up with. You can use it to successfully include un-compiled assets in the template HTML file, but the <link> line will disappear when the file is processed as a lodash template by html-webpack. If you configure html-webpack to minify HTML (remove comments), all three lines will disappear.
```
<!-- Comment trickery to drop this line when file is used as a lodash template for html-webpack-plugin <% /*-->
    <link rel="stylesheet" href="style.css" type="text/css">
<!-- */ %> -->
```
Edit: I'm not sure if lodash guarantees to always parse the comments in the way required for this to work, so maybe it fails to work on some future/past lodash version.
