### ISSUE TITLE
Doesn't work with webpack --watch

### ISSUE THREAD

**Issue by andybarron** [DustinJackson/html-webpack-inline-source-plugin#5]
It rebuilds the bundled .js file, but not the inlined HTML.

**Comment by d-bitz** [comment]
This is most likely because of html-webpack-plugin's caching mechanism.  From it's perspective the html file it generates hasn't changed (i.e. the reference to bundle.js is the same).  This inline source plugin works by altering tag definitions generated by html-webpack-plugin, since a new html file isn't emitted the inline source doesn't get updated...

For a quick fix try setting `cache: false` in your [configuration](https://github.com/ampedandwired/html-webpack-plugin#configuration).
